// Code generated by protoc-gen-go-xhttp. DO NOT EDIT.
// versions:
// protoc-gen-go-xhttp v1.0.0

package v1

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	transport "github.com/go-kratos/kratos/v2/transport"
	xhttp "github.com/go-kratos/kratos/v2/transport/xhttp"
	apistate "github.com/go-kratos/kratos/v2/transport/xhttp/apistate"
	binding "github.com/go-kratos/kratos/v2/transport/xhttp/binding"
)

import fiber "github.com/gofiber/fiber/v2"

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.BindBody

const _ = xhttp.SupportPackageIsVersion1
const _ = middleware.SupportPackageIsVersion1
const _ = transport.KindXHTTP

var _ = new(apistate.Resp[any])

// 角色服务
type RoleXHTTPServer interface {
	CreateRole(context.Context, *RoleRequest) (*IDReply, error)
	DeleteRole(context.Context, *IDsRequest) (*EmptyReply, error)
	GetRole(context.Context, *IDRequest) (*RoleReply, error)
	ListRole(context.Context, *ListRequest) (*ListRoleReply, error)
	UpdateRole(context.Context, *RoleRequest) (*IDReply, error)
}

func RegisterRoleXHTTPServer(s *xhttp.Server, srv RoleXHTTPServer) {
	s.Route(func(r fiber.Router) {
		api := r.Group("api/system/v1/role")
		// Register all service annotation
		{
			api.Name("Role-XHTTPServer")
			api.Use(middleware.Authenticator(), middleware.Authorizer())
		}
		api.Post("/", _Role_CreateRole0_XHTTP_Handler(srv)).Name("Role-CreateRole.0-XHTTP_Handler")
		api.Put("/", _Role_UpdateRole0_XHTTP_Handler(srv)).Name("Role-UpdateRole.0-XHTTP_Handler")
		api.Delete("/:ids", _Role_DeleteRole0_XHTTP_Handler(srv)).Name("Role-DeleteRole.0-XHTTP_Handler")
		api.Get("/:id", _Role_GetRole0_XHTTP_Handler(srv)).Name("Role-GetRole.0-XHTTP_Handler")
		api.Get("/list", _Role_ListRole0_XHTTP_Handler(srv)).Name("Role-ListRole.0-XHTTP_Handler")
	})
}

func _Role_CreateRole0_XHTTP_Handler(srv RoleXHTTPServer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var in RoleRequest
		if err := binding.BindBody(c, &in); err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		ctx := transport.NewFiberContext(context.Background(), c)
		reply, err := srv.CreateRole(ctx, &in)
		if err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		return apistate.Success[*IDReply]().WithData(reply).Send(c)
	}
}

func _Role_UpdateRole0_XHTTP_Handler(srv RoleXHTTPServer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var in RoleRequest
		if err := binding.BindBody(c, &in); err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		ctx := transport.NewFiberContext(context.Background(), c)
		reply, err := srv.UpdateRole(ctx, &in)
		if err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		return apistate.Success[*IDReply]().WithData(reply).Send(c)
	}
}

func _Role_DeleteRole0_XHTTP_Handler(srv RoleXHTTPServer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var in IDsRequest
		if err := binding.BindParams(c, &in); err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		ctx := transport.NewFiberContext(context.Background(), c)
		reply, err := srv.DeleteRole(ctx, &in)
		if err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		return apistate.Success[*EmptyReply]().WithData(reply).Send(c)
	}
}

func _Role_GetRole0_XHTTP_Handler(srv RoleXHTTPServer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var in IDRequest
		if err := binding.BindParams(c, &in); err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		ctx := transport.NewFiberContext(context.Background(), c)
		reply, err := srv.GetRole(ctx, &in)
		if err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		return apistate.Success[*RoleReply]().WithData(reply).Send(c)
	}
}

func _Role_ListRole0_XHTTP_Handler(srv RoleXHTTPServer) fiber.Handler {
	return func(c *fiber.Ctx) error {
		var in ListRequest
		if err := binding.BindQuery(c, &in); err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		ctx := transport.NewFiberContext(context.Background(), c)
		reply, err := srv.ListRole(ctx, &in)
		if err != nil {
			return apistate.Error[any]().WithError(err).Send(c)
		}
		return apistate.Success[*ListRoleReply]().WithData(reply).Send(c)
	}
}
