// Code generated by protoc-gen-go-xhttp. DO NOT EDIT.
// versions:
// protoc-gen-go-xhttp v1.0.0

package v1

import (
	context "context"
	middleware "github.com/go-kratos/kratos/v2/middleware"
	xhttp "github.com/go-kratos/kratos/v2/transport/xhttp"
	apistate "github.com/go-kratos/kratos/v2/transport/xhttp/apistate"
	binding "github.com/go-kratos/kratos/v2/transport/xhttp/binding"
	"github.com/gofiber/fiber/v2"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.BindBody

const _ = xhttp.SupportPackageIsVersion1
const _ = middleware.SupportPackageIsVersion1

var _ = new(apistate.Resp)

// 用户服务
type UserXHTTPServer interface {
	CreateUser(context.Context, *UserRequest) (*IDReply, error)
	DeleteUser(context.Context, *IDRequest) (*EmptyReply, error)
	GetUser(context.Context, *IDRequest) (*UserReply, error)
	ListUser(context.Context, *ListRequest) (*ListUserReply, error)
	UpdatePassword(context.Context, *PasswordRequest) (*IDReply, error)
	UpdateUser(context.Context, *UserRequest) (*IDReply, error)
	UpdateUserStatus(context.Context, *IDRequest) (*IDReply, error)
}

func RegisterUserXHTTPServer(s *xhttp.Server, srv UserXHTTPServer) {
	s.Route(func(r fiber.Router) {
		api := r.Group("api/system/v1/user")
		// Register all service annotation
		{
			api.Use(middleware.Authenticator(), middleware.Authorizer())
		}
		api.Post("/", _User_CreateUser0_XHTTP_Handler(srv))
		api.Put("/", _User_UpdateUser0_XHTTP_Handler(srv))
		api.Put("/password", _User_UpdatePassword0_XHTTP_Handler(srv))
		api.Put("/status", _User_UpdateUserStatus0_XHTTP_Handler(srv))
		api.Delete("/:id", _User_DeleteUser0_XHTTP_Handler(srv))
		api.Get("/:id", _User_GetUser0_XHTTP_Handler(srv))
		api.Post("/list", _User_ListUser0_XHTTP_Handler(srv))
	})
}

//
func _User_CreateUser0_XHTTP_Handler(srv UserXHTTPServer) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var in UserRequest
		if err := binding.BindBody(ctx, &in); err != nil {
			return err
		}
		reply, err := srv.CreateUser(ctx.Context(), &in)
		if err != nil {
			return apistate.Error().WithError(err).Send(ctx)
		}
		return apistate.Success().WithData(reply).Send(ctx)
	}
}

//
func _User_UpdateUser0_XHTTP_Handler(srv UserXHTTPServer) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var in UserRequest
		if err := binding.BindBody(ctx, &in); err != nil {
			return err
		}
		reply, err := srv.UpdateUser(ctx.Context(), &in)
		if err != nil {
			return apistate.Error().WithError(err).Send(ctx)
		}
		return apistate.Success().WithData(reply).Send(ctx)
	}
}

//
func _User_UpdatePassword0_XHTTP_Handler(srv UserXHTTPServer) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var in PasswordRequest
		if err := binding.BindBody(ctx, &in); err != nil {
			return err
		}
		reply, err := srv.UpdatePassword(ctx.Context(), &in)
		if err != nil {
			return apistate.Error().WithError(err).Send(ctx)
		}
		return apistate.Success().WithData(reply).Send(ctx)
	}
}

//
func _User_UpdateUserStatus0_XHTTP_Handler(srv UserXHTTPServer) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var in IDRequest
		if err := binding.BindBody(ctx, &in); err != nil {
			return err
		}
		reply, err := srv.UpdateUserStatus(ctx.Context(), &in)
		if err != nil {
			return apistate.Error().WithError(err).Send(ctx)
		}
		return apistate.Success().WithData(reply).Send(ctx)
	}
}

//
func _User_DeleteUser0_XHTTP_Handler(srv UserXHTTPServer) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var in IDRequest
		if err := binding.BindParams(ctx, &in); err != nil {
			return err
		}
		reply, err := srv.DeleteUser(ctx.Context(), &in)
		if err != nil {
			return apistate.Error().WithError(err).Send(ctx)
		}
		return apistate.Success().WithData(reply).Send(ctx)
	}
}

//
func _User_GetUser0_XHTTP_Handler(srv UserXHTTPServer) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var in IDRequest
		if err := binding.BindParams(ctx, &in); err != nil {
			return err
		}
		reply, err := srv.GetUser(ctx.Context(), &in)
		if err != nil {
			return apistate.Error().WithError(err).Send(ctx)
		}
		return apistate.Success().WithData(reply).Send(ctx)
	}
}

//
func _User_ListUser0_XHTTP_Handler(srv UserXHTTPServer) fiber.Handler {
	return func(ctx *fiber.Ctx) error {
		var in ListRequest
		if err := binding.BindBody(ctx, &in); err != nil {
			return err
		}
		reply, err := srv.ListUser(ctx.Context(), &in)
		if err != nil {
			return apistate.Error().WithError(err).Send(ctx)
		}
		return apistate.Success().WithData(reply).Send(ctx)
	}
}
