// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"kratosx-fashion/app/system/internal/data/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
)

func newRoleMenu(db *gorm.DB) roleMenu {
	_roleMenu := roleMenu{}

	_roleMenu.roleMenuDo.UseDB(db)
	_roleMenu.roleMenuDo.UseModel(&model.RoleMenu{})

	tableName := _roleMenu.roleMenuDo.TableName()
	_roleMenu.ALL = field.NewField(tableName, "*")
	_roleMenu.ID = field.NewUint(tableName, "id")
	_roleMenu.CreatedAt = field.NewTime(tableName, "created_at")
	_roleMenu.UpdatedAt = field.NewTime(tableName, "updated_at")
	_roleMenu.DeletedAt = field.NewField(tableName, "deleted_at")
	_roleMenu.RoleID = field.NewUint64(tableName, "role_id")
	_roleMenu.MenuID = field.NewUint64(tableName, "menu_id")
	_roleMenu.ActionID = field.NewUint64(tableName, "action_id")

	_roleMenu.fillFieldMap()

	return _roleMenu
}

type roleMenu struct {
	roleMenuDo roleMenuDo

	ALL       field.Field
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	RoleID    field.Uint64
	MenuID    field.Uint64
	ActionID  field.Uint64

	fieldMap map[string]field.Expr
}

func (r roleMenu) Table(newTableName string) *roleMenu {
	r.roleMenuDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roleMenu) As(alias string) *roleMenu {
	r.roleMenuDo.DO = *(r.roleMenuDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roleMenu) updateTableName(table string) *roleMenu {
	r.ALL = field.NewField(table, "*")
	r.ID = field.NewUint(table, "id")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewField(table, "deleted_at")
	r.RoleID = field.NewUint64(table, "role_id")
	r.MenuID = field.NewUint64(table, "menu_id")
	r.ActionID = field.NewUint64(table, "action_id")

	r.fillFieldMap()

	return r
}

func (r *roleMenu) WithContext(ctx context.Context) *roleMenuDo { return r.roleMenuDo.WithContext(ctx) }

func (r roleMenu) TableName() string { return r.roleMenuDo.TableName() }

func (r *roleMenu) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roleMenu) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 7)
	r.fieldMap["id"] = r.ID
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
	r.fieldMap["role_id"] = r.RoleID
	r.fieldMap["menu_id"] = r.MenuID
	r.fieldMap["action_id"] = r.ActionID
}

func (r roleMenu) clone(db *gorm.DB) roleMenu {
	r.roleMenuDo.ReplaceDB(db)
	return r
}

type roleMenuDo struct{ gen.DO }

func (r roleMenuDo) Debug() *roleMenuDo {
	return r.withDO(r.DO.Debug())
}

func (r roleMenuDo) WithContext(ctx context.Context) *roleMenuDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roleMenuDo) Clauses(conds ...clause.Expression) *roleMenuDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roleMenuDo) Returning(value interface{}, columns ...string) *roleMenuDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roleMenuDo) Not(conds ...gen.Condition) *roleMenuDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roleMenuDo) Or(conds ...gen.Condition) *roleMenuDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roleMenuDo) Select(conds ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roleMenuDo) Where(conds ...gen.Condition) *roleMenuDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roleMenuDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *roleMenuDo {
	return r.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (r roleMenuDo) Order(conds ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roleMenuDo) Distinct(cols ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roleMenuDo) Omit(cols ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roleMenuDo) Join(table schema.Tabler, on ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roleMenuDo) LeftJoin(table schema.Tabler, on ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roleMenuDo) RightJoin(table schema.Tabler, on ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roleMenuDo) Group(cols ...field.Expr) *roleMenuDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roleMenuDo) Having(conds ...gen.Condition) *roleMenuDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roleMenuDo) Limit(limit int) *roleMenuDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roleMenuDo) Offset(offset int) *roleMenuDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roleMenuDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *roleMenuDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roleMenuDo) Unscoped() *roleMenuDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roleMenuDo) Create(values ...*model.RoleMenu) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roleMenuDo) CreateInBatches(values []*model.RoleMenu, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roleMenuDo) Save(values ...*model.RoleMenu) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roleMenuDo) First() (*model.RoleMenu, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenu), nil
	}
}

func (r roleMenuDo) Take() (*model.RoleMenu, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenu), nil
	}
}

func (r roleMenuDo) Last() (*model.RoleMenu, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenu), nil
	}
}

func (r roleMenuDo) Find() ([]*model.RoleMenu, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoleMenu), err
}

func (r roleMenuDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoleMenu, err error) {
	buf := make([]*model.RoleMenu, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roleMenuDo) FindInBatches(result *[]*model.RoleMenu, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roleMenuDo) Attrs(attrs ...field.AssignExpr) *roleMenuDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roleMenuDo) Assign(attrs ...field.AssignExpr) *roleMenuDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roleMenuDo) Joins(field field.RelationField) *roleMenuDo {
	return r.withDO(r.DO.Joins(field))
}

func (r roleMenuDo) Preload(field field.RelationField) *roleMenuDo {
	return r.withDO(r.DO.Preload(field))
}

func (r roleMenuDo) FirstOrInit() (*model.RoleMenu, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenu), nil
	}
}

func (r roleMenuDo) FirstOrCreate() (*model.RoleMenu, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoleMenu), nil
	}
}

func (r roleMenuDo) FindByPage(offset int, limit int) (result []*model.RoleMenu, count int64, err error) {
	if limit <= 0 {
		count, err = r.Count()
		return
	}

	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roleMenuDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r *roleMenuDo) withDO(do gen.Dao) *roleMenuDo {
	r.DO = *do.(*gen.DO)
	return r
}
