// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"kratosx-fashion/app/system/internal/biz"
	"kratosx-fashion/app/system/internal/conf"
	"kratosx-fashion/app/system/internal/data"
	"kratosx-fashion/app/system/internal/data/infra"
	"kratosx-fashion/app/system/internal/data/repo"
	"kratosx-fashion/app/system/internal/middleware"
	"kratosx-fashion/app/system/internal/server"
	"kratosx-fashion/app/system/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, storage *conf.Storage, confData *conf.Data, jwt *conf.JWT, logger *conf.Logger) (*kratos.App, func(), error) {
	logLogger := infra.NewLogger(logger)
	db := data.NewDB(confData, logLogger)
	client := data.NewRedis(confData, logLogger)
	dataData, cleanup, err := data.NewData(confData, logLogger, db, client)
	if err != nil {
		return nil, nil, err
	}
	jwtRepo := repo.NewJwtRepo(dataData, jwt, logLogger)
	jwtService := middleware.NewJwtService(jwtRepo, logLogger)
	syncedEnforcer := data.NewCasbin(confData, db, logLogger)
	casbinAuth := middleware.NewCasbinAuth(syncedEnforcer, logLogger)
	cache := middleware.NewCache()
	limiter := middleware.NewLimiter()
	globalMiddleware := middleware.NewGlobalMiddleware(logLogger)
	userRepo := repo.NewUserRepo(dataData, logLogger)
	userRoleRepo := repo.NewUserRoleRepo(dataData, logLogger)
	ip2locationDB := data.NewIPLocationDB(confData, logLogger)
	loginLogRepo := repo.NewLoginLogRepo(dataData, logLogger, ip2locationDB)
	captchaRepo := repo.NewCaptchaRepo(logLogger)
	storageStorage := infra.NewStorage(storage)
	publicUsecase := biz.NewPublicUsecase(userRepo, userRoleRepo, loginLogRepo, captchaRepo, jwtRepo, storageStorage, client, logLogger)
	pubService := service.NewPubService(publicUsecase, logLogger)
	roleRepo := repo.NewRoleRepo(dataData, logLogger)
	transaction := data.NewTransaction(dataData)
	userUsecase := biz.NewUserUsecase(jwtRepo, userRepo, userRoleRepo, roleRepo, loginLogRepo, transaction, logLogger)
	userService := service.NewUserService(userUsecase, logLogger)
	resourceRouterRepo := repo.NewResourceRouterRepo(dataData, logLogger, syncedEnforcer)
	roleResourceRepo := repo.NewRoleResourceRepo(dataData, logLogger)
	roleUsecase := biz.NewRoleUsecase(roleRepo, userRoleRepo, resourceRouterRepo, roleResourceRepo, transaction, logLogger)
	roleService := service.NewRoleService(roleUsecase, logLogger)
	resourceMenuRepo := repo.NewResourceMenuRepo(dataData, logLogger)
	resourceUsecase := biz.NewResourceUsecase(resourceMenuRepo, resourceRouterRepo, roleResourceRepo, transaction, logLogger)
	resourceService := service.NewResourceService(resourceUsecase, logLogger)
	xhttpServer := server.NewHTTPServer(confServer, jwtService, casbinAuth, cache, limiter, globalMiddleware, pubService, userService, roleService, resourceService, logLogger)
	registrar := infra.NewRegistrar(registry)
	app := newApp(logLogger, xhttpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
