version: "3"
services:
  kratosx-fashion:
    container_name: kratosx-fashion
    image: kratosx-fashion
    restart: unless-stopped
    ports:
     - 8000:8000
     - 9000:9000
    volumes:
      - ./log:/app/log
      - ./app/system/configs:/app/configs
      - ./resource:/app/resource
  kraotsx-gateway:
    container_name: kratosx-gateway
    image: nginx
    restart: on-failure
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./cert:/etc/nginx/ssl
      - ./nginx.conf:/etc/nginx/nginx.conf 
    environment:
      - TZ=Asia/Shanghai
