server:
  http:
    addr: 0.0.0.0:18000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 1s
data:
  database:
    driver: mysql
    source: ${DSN}
    log_mode: warn
    max_idle_conns: 10
    max_open_conns: 100
    auto_migrate: false
  redis:
    addr: ${REDIS_ADDR}
    password: ${REDIS_PASSWORD}
    read_timeout: 0.2s
    write_timeout: 0.2s
  iplocation:
    source: ./resource/IP2LOCATION-LITE-DB5.BIN
  casbin:
    source: ./resource/model.conf
logger:
  prefix: kratosx-fashion
  level: info
  format: console
  dir: log
  encode_level: CapitalColor
  stacktrace_key: stacktrace
  show_line: false
  log_in_console: true
jwt:
  secret: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC7VJTUt9Us8cKj
  issuer: paradox
  ttl: 86400s
  refresh_ttl: 604800s
algo:
  recommend_addr: 110.42.197.201:8087
  tryon_addr: region-11.autodl.com:14205