server:
  http:
    addr: 0.0.0.0:18000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/violet_test?charset=utf8mb4&parseTime=True&loc=Local
    log_mode: silent
    max_idle_conns: 10
    max_open_conns: 100
    auto_migrate: false
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  iplocation:
    source: ./resource/IP2LOCATION-LITE-DB5.BIN
  casbin:
    source: ./resource/model.conf
logger:
  prefix: kratosx-fashion:system
  level: info
  format: console
  dir: log
  encode_level: CapitalColor
  stacktrace_key: stacktrace
  show_line: false
  log_in_console: true
jwt:
  secret: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC7VJTUt9Us8cKj
  issuer: paradox
  ttl: 86400s
