type: oss # 驱动
disks:
  local:
    root_dir: ./storage/app # 本地存储根目录
    app_url: http://localhost:18000/storage # 本地图片 url 前部
  ali_oss:
    access_key_id: LTAI4G2VAprQQLzNDiu2dfC3
    access_key_secret: 2KVTBz4hVh1wpflVNeCPIVqDsjOtUL
    bucket: paradox-hyw
    endpoint: oss-cn-shanghai.aliyuncs.com
    is_ssl: true # 是否使用 https 协议
    is_private: false # 是否私有读