server:
  http:
    addr: 0.0.0.0:18000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:19000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/violet
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
logger:
  prefix: kratosx-fashion
  level: info
  format: console
  dir: log
  encode_level: CapitalColor
  stacktrace_key: stacktrace
  show_line: false
  log_in_console: true
