name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'violet_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: '123456' # Required if "mysql user" is empty, default is empty. The root superuser password

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Init
        run: cd app/system && make init

      - name: System Generate
        run: cd app/system && make all

      - name: Fashion Generate
        run: cd app/fashion && make all

      - name: Build
        run: cd app/system && make build

      - name: SCP Files
        uses: appleboy/scp-action@master
        with:
            host: ${{ secrets.REMOTE_HOST }}  # Secrets中的配置：vps IP地址
            username: ${{ secrets.REMOTE_USER }}  # Secrets中的配置：vps 登录用户名
            port: 22 # Secrets中的配置：vps 端口
            key: ${{ secrets.REMOTE_SSH_KEY }} # Secrets中的配置：vps 上创建的ssh key的私钥内容
            source: 'app/system/bin,deploy/,app/system/configs'  # 编译出的二进制文件名
            target: ${{ secrets.REMOTE_TARGET }} # Secrets中的配置：scp 到 vps 上的的目录

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2