name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
          mysql database: 'violet_test' # Optional, default value is "test". The specified database which will be create
          mysql root password: '123456' # Required if "mysql user" is empty, default is empty. The root superuser password

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Init
        run: cd app/system && make init

      - name: System Generate
        run: cd app/system && make all

      - name: Fashion Generate
        run: cd app/fashion && make all

      - name: Build
        run: cd app/system && make build

      - name: Docker Build
        run: cd app/system && make docker

      - name: Docker Login
        run: docker login hkccr.ccs.tencentyun.com --username=${{ secrets.DOCKER_REPO_USERNAME }} --password=${{ secrets.DOCKER_REPO_PASSWORD }}

      - name: Docker Push
        run: docker tag ${{ secrets.REMOTE_TARGET }} hkccr.ccs.tencentyun.com/mirror_repo/mirror_repo:latest && docker push hkccr.ccs.tencentyun.com/mirror_repo/${{ secrets.REMOTE_TARGET }}:latest

      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
